"""package_version imported_from

Revision ID: bb7c542c7246
Revises: 0b257b4e70af
Create Date: 2026-04-25 09:53:28.297064

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bb7c542c7246"
down_revision: str | None = "0b257b4e70af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("imported_from", sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.drop_column("imported_from")

    # ### end Alembic commands ###
