"""channel_members acl table

Revision ID: 47a826dd28a0
Revises: 56a65a1c8d76
Create Date: 2026-04-24 19:11:16.244911

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47a826dd28a0"
down_revision: str | None = "56a65a1c8d76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(user_id IS NULL) <> (group_name IS NULL)", name="ck_channel_member_principal_xor"
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "group_name", name="uq_channel_member_group"),
        sa.UniqueConstraint("channel_id", "user_id", name="uq_channel_member_user"),
    )
    with op.batch_alter_table("channel_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_members_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_members_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_channel_members_channel_id"))

    op.drop_table("channel_members")
    # ### end Alembic commands ###
