"""channel mirror columns

Revision ID: 56a65a1c8d76
Revises: d85806f06ac0
Create Date: 2026-04-24 10:09:27.345080

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "56a65a1c8d76"
down_revision: str | None = "d85806f06ac0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default on mirror_cache_seconds so existing channels get a sane
    # value during the add; downstream ORM default takes over on new rows.
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mirror_url", sa.String(length=512), nullable=True))
        batch_op.add_column(
            sa.Column(
                "mirror_cache_seconds",
                sa.Integer(),
                nullable=False,
                server_default="900",
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_column("mirror_cache_seconds")
        batch_op.drop_column("mirror_url")

    # ### end Alembic commands ###
