"""package_version about metadata

Revision ID: 5781ad0717a3
Revises: c724a4e4b797
Create Date: 2026-08-22 21:30:41.201450

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5781ad0717a3"
down_revision: str | None = "c724a4e4b797"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doc_url", sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column("home", sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column("dev_url", sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column("summary", sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("about_fetched_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.drop_column("about_fetched_at")
        batch_op.drop_column("description")
        batch_op.drop_column("summary")
        batch_op.drop_column("dev_url")
        batch_op.drop_column("home")
        batch_op.drop_column("doc_url")

    # ### end Alembic commands ###
