"""import jobs table

Revision ID: c724a4e4b797
Revises: bb7c542c7246
Create Date: 2026-04-25 13:14:07.242844

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c724a4e4b797"
down_revision: str | None = "bb7c542c7246"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("upstream_url", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("written_bytes", sa.BigInteger(), nullable=False),
        sa.Column("current_filename", sa.String(length=512), nullable=True),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_jobs_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_jobs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_import_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_import_jobs_channel_id"))

    op.drop_table("import_jobs")
    # ### end Alembic commands ###
