"""initial schema

Revision ID: d85806f06ac0
Revises:
Create Date: 2026-04-24 06:25:02.020117

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d85806f06ac0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("storage_prefix", sa.String(length=512), nullable=False),
        sa.Column("repodata_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channels_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_subject"), ["subject"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "name", name="uq_package_channel_name"),
    )
    with op.batch_alter_table("packages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_packages_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_packages_name"), ["name"], unique=False)

    op.create_table(
        "package_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("build", sa.String(length=128), nullable=False),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("subdir", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("md5", sa.String(length=32), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("depends", sa.JSON(), nullable=False),
        sa.Column("constrains", sa.JSON(), nullable=False),
        sa.Column("package_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "package_id", "version", "build", "subdir", name="uq_packageversion_unique"
        ),
    )
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_package_versions_filename"), ["filename"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_package_versions_package_id"), ["package_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_package_versions_subdir"), ["subdir"], unique=False)
        batch_op.create_index(batch_op.f("ix_package_versions_version"), ["version"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_package_versions_version"))
        batch_op.drop_index(batch_op.f("ix_package_versions_subdir"))
        batch_op.drop_index(batch_op.f("ix_package_versions_package_id"))
        batch_op.drop_index(batch_op.f("ix_package_versions_filename"))

    op.drop_table("package_versions")
    with op.batch_alter_table("packages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_packages_name"))
        batch_op.drop_index(batch_op.f("ix_packages_channel_id"))

    op.drop_table("packages")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_subject"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channels_name"))

    op.drop_table("channels")
    # ### end Alembic commands ###
